### ISSUE TITLE
Cryptography libraries missing in the browser implementation

### ISSUE THREAD

**Issue by JoaoPere** [mnasyrov/cryptobench-js#3]
My bad, missed the browser instructions.

**Comment by mnasyrov** [comment]
No problem. I slightly updated the doc to make the section be more visible.

**Comment by JoaoPere** [comment]
I actually found another issue trying to run the browser version, may I open another thread?

Anyway, long story short, the `crypto-js` instance for the vendorCopy array does not have the correct input directory. It stands as this;

    {
      "from": "./bower_components_/crypto-js/crypto-js.js",
      "to": "./www/vendor/crypto-js.js"
    }

When in fact it is under the `node_modules` directory, generating

    {
      "from": "./node_modules/crypto-js/crypto-js.js",
      "to": "./www/vendor/crypto-js.js"
    }

**Comment by mnasyrov** [comment]
Thank you for noticing this one! I reopen the issue for this case.

**Comment by mnasyrov** [comment]
Fixed.
